---
- name: Windows Update
  hosts: domainmember
  tasks:
  - name: Install updates
    ansible.windows.win_updates:
      category_names: '*'
      skip_optional: false
      reboot: true
      reboot_timeout: 3600
